version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/001_init_up.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend-network

  centrifugo:
    image: centrifugo/centrifugo:latest
    container_name: centrifugo
    command: centrifugo -c config.json --port=8900 --admin
    ports:
      - "8900:8900"
    volumes:
      - ./config.json:/centrifugo/config.json
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    name: "backend-network"
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.243.0/24

volumes:
  postgres_data: { }
