version: '3.8'

services:
  centrifugo:
    image: centrifugo/centrifugo:latest
    container_name: centrifugo
    command: centrifugo -c config.json --port=8900 --admin
    ports:
      - "8900:8900"
    volumes:
      - ./config.json:/centrifugo/config.json
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    name: "backend-network"
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.243.0/24

volumes:
  postgres_data: { }
