// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock_session is a generated GoMock package.
package mock_session

import (
	context "context"
	model "project/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateSessionById mocks base method.
func (m *MockUsecase) CreateSessionById(ctx context.Context, userID uint64) (model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionById", ctx, userID)
	ret0, _ := ret[0].(model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionById indicates an expected call of CreateSessionById.
func (mr *MockUsecaseMockRecorder) CreateSessionById(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionById", reflect.TypeOf((*MockUsecase)(nil).CreateSessionById), ctx, userID)
}

// DeleteSessionByCookie mocks base method.
func (m *MockUsecase) DeleteSessionByCookie(ctx context.Context, cookie string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionByCookie", ctx, cookie)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionByCookie indicates an expected call of DeleteSessionByCookie.
func (mr *MockUsecaseMockRecorder) DeleteSessionByCookie(ctx, cookie interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionByCookie", reflect.TypeOf((*MockUsecase)(nil).DeleteSessionByCookie), ctx, cookie)
}

// GetSessionByCookie mocks base method.
func (m *MockUsecase) GetSessionByCookie(ctx context.Context, cookie string) (model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByCookie", ctx, cookie)
	ret0, _ := ret[0].(model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByCookie indicates an expected call of GetSessionByCookie.
func (mr *MockUsecaseMockRecorder) GetSessionByCookie(ctx, cookie interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByCookie", reflect.TypeOf((*MockUsecase)(nil).GetSessionByCookie), ctx, cookie)
}
