// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: producer_rpc.proto

package service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protobuf_generated "project/internal/model/generated"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProducersClient is the client API for Producers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProducersClient interface {
	ProduceMessage(ctx context.Context, in *protobuf_generated.Bytes, opts ...grpc.CallOption) (*empty.Empty, error)
}

type producersClient struct {
	cc grpc.ClientConnInterface
}

func NewProducersClient(cc grpc.ClientConnInterface) ProducersClient {
	return &producersClient{cc}
}

func (c *producersClient) ProduceMessage(ctx context.Context, in *protobuf_generated.Bytes, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.Producers/ProduceMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducersServer is the server API for Producers service.
// All implementations should embed UnimplementedProducersServer
// for forward compatibility
type ProducersServer interface {
	ProduceMessage(context.Context, *protobuf_generated.Bytes) (*empty.Empty, error)
}

// UnimplementedProducersServer should be embedded to have forward compatible implementations.
type UnimplementedProducersServer struct {
}

func (UnimplementedProducersServer) ProduceMessage(context.Context, *protobuf_generated.Bytes) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceMessage not implemented")
}

// UnsafeProducersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducersServer will
// result in compilation errors.
type UnsafeProducersServer interface {
	mustEmbedUnimplementedProducersServer()
}

func RegisterProducersServer(s grpc.ServiceRegistrar, srv ProducersServer) {
	s.RegisterService(&Producers_ServiceDesc, srv)
}

func _Producers_ProduceMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protobuf_generated.Bytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducersServer).ProduceMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Producers/ProduceMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducersServer).ProduceMessage(ctx, req.(*protobuf_generated.Bytes))
	}
	return interceptor(ctx, in, info, handler)
}

// Producers_ServiceDesc is the grpc.ServiceDesc for Producers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Producers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Producers",
	HandlerType: (*ProducersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProduceMessage",
			Handler:    _Producers_ProduceMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "producer_rpc.proto",
}
