Server:
  port: ":8081"

Postgres:
  db: "postgres"
  connectionToDB: "user=brigade password=123 dbname=brigade host=postgres port=5432 sslmode=disable" #postgres host=postgres

Cors:
  allowMethods:
    - "POST"
    - "PUT"
    - "GET"
    - "DELETE"
    - "OPTIONS"
  allowOrigins:
    - "http://95.163.249.116"
    - "http://localhost:10000"
  allowHeaders:
    - "Content-Type"
    - "Content-Length"
    - "X-Csrf-Token"
  allowCredentials: true

Redis:
  addr: "redis:6379"

Minio:
  endpoint: "minio:9000"
  username: "minio"
  password: "minio123"
  token: ""

Kafka:
  brokerList:
    - "kafka:9092"
  groupID: "messages"

ChatsService:
  addr: "localhost:9000"
  addrMetrics: "localhost:9091"
  serviceName: "chat"

UsersService:
  addr: "localhost:9001"
  addrMetrics: "localhost:9092"
  serviceName: "user"

MessagesService:
  addr: "localhost:9002"
  addrMetrics: "localhost:9093"
  serviceName: "messages"

ConsumerService:
  addr: "localhost:9003"
  addrMetrics: "localhost:9094"
  serviceName: "consumer"

ProducerService:
  addr: "localhost:9004"
  addrMetrics: "localhost:9095"
  serviceName: "producer"

AuthService:
  addr: "localhost:9005"
  addrMetrics: "localhost:9096"
  serviceName: "auth"
