Server:
  port: ":8081"

Postgres:
  db: "postgres"
  connectionToDB: "user=brigade password=123 dbname=brigade host=postgres port=5432 sslmode=disable" #postgres host=postgres

Cors:
  allowMethods:
    - "POST"
    - "PUT"
    - "GET"
    - "DELETE"
    - "OPTIONS"
  allowOrigins:
    - "http://95.163.249.116"
    - "http://localhost:10000"
  allowHeaders:
    - "Content-Type"
    - "Content-Length"
    - "X-Csrf-Token"
  allowCredentials: true

Redis:
  addr: "redis:6379"

Minio:
  endpoint: "minio:9000"
  username: "minio"
  password: "minio123"
  token: ""

Kafka:
  brokerList:
    - "kafka:9092"
  groupID: "messages"

ChatsService:
  addr: "chat:9000"

UsersService:
  addr: "user:9001"

MessagesService:
  addr: "messages:9002"

ConsumerService:
  addr: "consumer:9003"

ProducerService:
  addr: "producer:9004"

AuthService:
  addr: "auth:9005"
