Server:
  port: ":8081"

Postgres:
  db: "postgres"
  connectionToDB: "user=brigade password=123 dbname=brigade host=postgres port=5432 sslmode=disable" #postgres host=postgres

Cors:
  allowMethods:
    - "POST"
    - "PUT"
    - "GET"
    - "DELETE"
    - "OPTIONS"
  allowOrigins:
    - "http://95.163.249.116"
    - "http://localhost:10000"
  allowHeaders:
    - "Content-Type"
    - "Content-Length"
    - "X-CSRF-Token"
  allowCredentials: true

Redis:
  addr: "redis:6379"

Minio:
  endpoint: "minio:9000"
  username: "minio"
  password: "minio123"
  token: ""

Kafka:
  brokerList:
    - "kafka:9092"
  groupID: "group-message"
