// Code generated by MockGen. DO NOT EDIT.
// Source: authservice.go

// Package mockAuthService is a generated GoMock package.
package mocks

import (
	context "context"
	"net/http"
	"project/internal/model"
	reflect "reflect"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockAuthService creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetUserById mocks base method.
func (m *MockUsecase) GetUserById(ctx context.Context, userID uint64) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, userID)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of Auth.
func (mr *MockUsecaseMockRecorder) GetUserById(ctx context.Context, userID uint64) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockUsecase)(nil).GetUserById), ctx, userID)
}

// ParsingIdUrl mocks base method.
func (m *MockUsecase) ParsingIdUrl(r *http.Request, param string) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParsingIdUrl", r, param)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// ParsingIdUrl indicates an expected call of Auth.
func (mr *MockUsecaseMockRecorder) ParsingIdUrl(r *http.Request, param string) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParsingIdUrl", reflect.TypeOf((*MockUsecase)(nil).ParsingIdUrl), r, param)
}
