// Code generated by MockGen. DO NOT EDIT.
// Source: authservice.go

// Package mockAuthService is a generated GoMock package.
package mocks

import (
	"github.com/labstack/echo/v4"
	"project/internal/model"
	reflect "reflect"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockAuthService creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetChatById mocks base method.
func (m *MockUsecase) GetChatById(ctx echo.Context, chatID uint64) (model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatById", ctx, chatID)
	ret0, _ := ret[0].(model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatById indicates an expected call of Auth.
func (mr *MockUsecaseMockRecorder) GetChatById(ctx echo.Context, chatID uint64) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatById", reflect.TypeOf((*MockUsecase)(nil).GetChatById), ctx, chatID)
}

// CreateChat mocks base method.
func (m *MockUsecase) CreateChat(ctx echo.Context, chat model.CreateChat) (model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, chat)
	ret0, _ := ret[0].(model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of Auth.
func (mr *MockUsecaseMockRecorder) CreateChat(ctx echo.Context, chat model.CreateChat) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockUsecase)(nil).CreateChat), ctx, chat)
}

// DeleteChatById mocks base method.
func (m *MockUsecase) DeleteChatById(ctx echo.Context, chatID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChatById", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChatById indicates an expected call of Auth.
func (mr *MockUsecaseMockRecorder) DeleteChatById(ctx echo.Context, chatID uint64) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChatById", reflect.TypeOf((*MockUsecase)(nil).DeleteChatById), ctx, chatID)
}

// CheckExistUserInChat mocks base method.
func (m *MockUsecase) CheckExistUserInChat(ctx echo.Context, chat model.Chat, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistUserInChat", ctx, chat, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckExistUserInChat indicates an expected call of Auth.
func (mr *MockUsecaseMockRecorder) CheckExistUserInChat(ctx echo.Context, chat model.Chat, userID uint64) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistUserInChat", reflect.TypeOf((*MockUsecase)(nil).CheckExistUserInChat), ctx, chat, userID)
}

// AddUserInChat mocks base method.
func (m *MockUsecase) AddUserInChat(ctx echo.Context, chatID uint64, memberID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserInChat", ctx, chatID, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserInChat indicates an expected call of Auth.
func (mr *MockUsecaseMockRecorder) AddUserInChat(ctx echo.Context, chatID uint64, memberID uint64) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserInChat", reflect.TypeOf((*MockUsecase)(nil).AddUserInChat), ctx, chatID, memberID)
}
