basePath: /
definitions:
  http.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Telegram wannabe
  title: Technogram
  version: 1.0.0
paths:
  /orders:
    post:
      consumes:
      - application/json
      description: Create a new order with the input paylod
      parameters:
      - description: Create order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/http.errorResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Create a new order
      tags:
      - orders
swagger: "2.0"
