name: CD

on:
  push:
    branches:
      - easyjson

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build docker-compose images
        run: . manage && build_compose ${{ github.sha }}

      - name: Log in dockerhub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Push docker-compose images to registry
        run: docker compose push
      
      - name: Copy docker-compose.yml config
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_HOST: ${{ secrets.HOST }}
          SOURCE: docker-compose.yml
          TARGET: /home/ubuntu/2023_1_Brigade/.docker-compose.yml
  
  stop-old-start-new:
    needs: build-n-push
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
        
      - name: Change directory
        run: cd /home/ubuntu/2023_1_Brigade
      
      - name: Pull docker-compose images
        run: docker compose -f .docker-compose.yml pull
      
      - name: Stop old cluster
        run: docker compose down || true
      
      - name: Set main docker-compose.yml to new config
        run: mv {.,}docker-compose.yml

      - name: Run new cluster
        run: docker compose up