name: CI

on:
  push:
    branches: 
      - dev
      - backend-dev
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go mod tidy

      - name: Run go vet
        run: go vet ./...

      - name: Install errcheck
        run: go install github.com/kisielk/errcheck@latest

      - name: Run errcheck
        run: errcheck ./...

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -race -vet=off ./...
